# ==============================================
# | SimpleLockpicking by ShermansWorld         |
# | A simple plugin for your lockpicking needs |
# ==============================================

config-version: 4

lang: "enUs"
# Possible languages: English (enUS)
# Interested in translating SimpleLockpicking?
# Let me know at https://www.spigotmc.org/threads/simplelockpicking.482879/ and provide the translation file

# Edit the meta for lockpicks
Lockpicks:
  DisplayName: "&e&lLockpick"
  Lore:
    - "&6A special tool to open locks. When used it"
    - "&6has a chance of opening a locked door or chest."

# The chance is 1 in [number]. For example if you wanted a 1 in 8 chance put 8.
# Iron is for iron doors and trapdoors, chests are for chests and trapped chests, wood is for everything else.
Chances:
  Iron: 10
  Chests: 5
  Wood: 5

# Remove the '#' from anything you want to prevent getting lockpicked  
Disabled:
  #- ACACIA_DOOR
  #- BIRCH_DOOR
  #- CRIMSON_DOOR
  #- DARK_OAK_DOOR
  #- JUNGLE_DOOR
  #- SPRUCE_DOOR
  #- WARPED_DOOR
  #- ACACIA_FENCE_GATE
  #- BIRCH_FENCE_GATE
  #- CRIMSON_FENCE_GATE
  #- DARK_OAK_FENCE_GATE
  #- JUNGLE_FENCE_GATE
  #- SPRUCE_FENCE_GATE
  #- WARPED_FENCE_GATE
  #- ACACIA_TRAPDOOR
  #- BIRCH_TRAPDOOR
  #- CRIMSON_TRAPDOOR
  #- DARK_OAK_TRAPDOOR
  #- JUNGLE_TRAPDOOR
  #- SPRUCE_TRAPDOOR
  #- WARPED_TRAPDOOR
  #- IRON_DOOR
  #- IRON_TRAPDOOR
  #- CHEST
  #- TRAPPED_CHEST

# Additional Options
ClosesAfterPicked: true
# If the above option is true this is how long a picked entrance will stay open
SecondsUntilCloses: 5

# ================================
# |     CRAFTBOOK OPTIONS        |
# ================================
# SimpleLockping now has CraftBook support!
# These settings only apply if you are using the CraftBook plugin

Gate:
   Enabled: true
   Chance: 5
Door:
   Enabled: true
   Chance: 5
Bridge:
   Enabled: true
   Chance: 5
      

